# Generated by Django 4.1.7 on 2023-03-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
