# Generated by Django 4.1.7 on 2023-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0005_userprofile_username_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
