# Generated by Django 4.1.7 on 2023-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0007_userprofile_avatar_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
